# Generated by Django 5.0.4 on 2024-04-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reader',
            options={'verbose_name_plural': 'List of Readers'},
        ),
        migrations.RemoveField(
            model_name='reader',
            name='name',
        ),
        migrations.AddField(
            model_name='reader',
            name='emailid',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reader',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
