# Generated by Django 5.0.4 on 2024-04-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0002_alter_reader_options_remove_reader_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
