# Generated by Django 5.0.4 on 2024-04-27 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0003_reader_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reader',
            options={},
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=20, null=True)),
                ('b_emailid', models.EmailField(max_length=254, null=True)),
                ('b_username', models.CharField(max_length=30, null=True)),
                ('b_date_of_borrow', models.DateField()),
                ('b_return_date', models.DateField()),
                ('b_idnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bb.reader')),
            ],
        ),
    ]
