# Generated by Django 5.0.4 on 2024-04-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0004_alter_reader_options_borrower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B_name', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Publisher', models.CharField(max_length=250)),
                ('Arrival_date', models.DateField()),
                ('Num_copy', models.CharField(max_length=30)),
            ],
        ),
    ]
