# Generated by Django 5.0.4 on 2024-04-28 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0006_rename_author_books_name_of_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='No_Of_copies_Available',
            new_name='No_of_copies_Available',
        ),
    ]
