# Generated by Django 5.0.4 on 2024-04-28 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0008_rename_no_of_copies_available_books_no_of_copies_available'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
