# Generated by Django 5.0.4 on 2024-04-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0010_alter_book_no_of_copies_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Name_of_Author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='Title',
            field=models.CharField(max_length=200),
        )
    ]
