# Generated by Django 5.0.4 on 2024-04-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0005_customer'),
        ('bb', '0011_alter_book_name_of_author_alter_book_title'),
    ]

    operations = [
    ]
