# Generated by Django 4.0.3 on 2024-05-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0014_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='No',
        ),
    ]
