# Generated by Django 5.0.4 on 2024-07-07 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0016_borrowedbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='b_idnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bb.customer'),
        ),
    ]
