# Generated by Django 5.0.4 on 2024-07-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0018_borrower_b_bookid'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='b_title',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
