# Generated by Django 5.0.4 on 2024-07-08 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0019_borrower_b_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='b_bookid',
        ),
        migrations.AlterField(
            model_name='borrower',
            name='b_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bb.book'),
        ),
    ]
