# Generated by Django 5.0.4 on 2024-07-13 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0020_remove_borrower_b_bookid_alter_borrower_b_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrower',
            old_name='b_title',
            new_name='b_bookid',
        ),
    ]
