# Generated by Django 5.0.4 on 2024-07-13 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0021_rename_b_title_borrower_b_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='b_bookid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bb.book'),
        ),
    ]
