# Generated by Django 5.0.4 on 2024-07-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0022_alter_borrower_b_bookid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='No_Of_copies_Available',
        ),
        migrations.AddField(
            model_name='book',
            name='No_of_Copies_Available',
            field=models.IntegerField(default=0),
        ),
    ]
